### ISSUE TITLE
spleeter folder not intializing - No module named 'spleeter.spleeter'

### ISSUE THREAD

**Issue by 8secz-johndpope** [rareguy/PySpleeterGUI#1]
git clone https://github.com/rareguy/PySpleeterGUI.git --recurse-submodules
I run this 
git submodule update --init --recursive

but I don't see spleeter 
I try dropping in this folder - 
<img width="1123" alt="Screen Shot 2020-04-04 at 8 45 23 pm" src="https://user-images.githubusercontent.com/50567111/78423885-3cd56e80-76b5-11ea-9c9e-5eb142d6ca39.png">

but still see
(spleeter-cpu) ➜  PySpleeterGUI git:(master) python main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from spleeter.spleeter.separator import Separator
ModuleNotFoundError: No module named 'spleeter.spleeter'

**Comment by 8secz-johndpope** [comment]
found this - https://github.com/8secz-johndpope/SpleetGUI

**Comment by rareguy** [comment]
Because it's a direct repository of Spleeter, you can just directly pull the repository directly to this repository.
And this is the one that you should pull:
![image](https://user-images.githubusercontent.com/33000326/78452934-a5721a80-76b8-11ea-97e6-e67ce347d5d2.png)
Because `spleeter.spleeter` means python is trying to access a folder named `spleeter` inside a `spleeter` folder, which doesn't exist if you pull from the folder you're mentioning.
![image](https://user-images.githubusercontent.com/33000326/78453192-4ad9be00-76ba-11ea-82a3-f3e972f46929.png)
Thank you for informing me, will update the Readme to clear this up, cheers.

**Comment by 8secz-johndpope** [comment]
thx

**Comment by 8secz-johndpope** [comment]
for some reason - on mac - having the spleeter/spleeter folder nested didn't work.

I managed to just drop in this folder directly 
<img width="398" alt="Screen Shot 2020-04-05 at 8 43 20 am" src="https://user-images.githubusercontent.com/50567111/78462849-85bf0e80-7719-11ea-811c-ad503138c4cb.png">

and record main.py to 

from spleeter.separator import Separator
from spleeter.utils import logging
import sys

then it works.
